### ISSUE TITLE
Determine the set of queries to show transaction boundaries

### ISSUE THREAD

**Issue by divsan93** [konveyor/tackle-data-gravity-insights#11]
**As a** Software Architect
**I need a** standard set of common queries that I can run against the KG
**So that** I can gain better insights into how my business transactions are structured

### Details & Assumptions

- We will use Neo4j for the Knowledge Graph (KG)
- We will use Neo4j Cypher query syntax to store the queries
- We will need a way for software architects to specify queries at a higher level than Cypher

### Acceptance Criteria

```gherkin
Given I have a set of standard queries
When the user selects a query
Then we can run it and show them meaningful results about transactions
```

**Comment by rofrano** [comment]
Available in Blume
