### ISSUE TITLE
Update the GitHub Pages documentation

### ISSUE THREAD

**Issue by rofrano** [konveyor/tackle-data-gravity-insights#77]
The `docs/getting-started.md` file was updated in #72 but the GitHub Pages documentation was never updated.

To put them back in sync, someone needs to:

1. Copy `getting-started.md` to the clipboard
2. Switch to the `gh-pages` branch
3. Carefully paste the changes into the version of `getting-started.md` in the `gh-pages` branch under the heading*.
4. Make a Pull Request to start the automation that builds the GitHub Pages web site.

***Note:** _The "heading" is the area at the top of the file that looks like this (don't delete it):_

```
---
layout: default
title: Getting Started
nav_order: 4
---
```

**Comment by fernandezbaptiste** [comment]
Hey rofrano, I'd like to help out on your issue. Are you still needing help with this? Thanks
