### ISSUE TITLE
Provide a way for the user to add partition information to method/classes

### ISSUE THREAD

**Issue by divsan93** [konveyor/tackle-data-gravity-insights#9]
**As a** user
**I need a** way to provide partitioning information to dgi.
**So that** I can understand how classes are segregated across partitions.

### Details & Assumptions

- A neo4j graph can be created with code2graph
- User has partitions as a txt file or a json file
- The classes in the partitions match (at least partially) the classes from code2graph
- If using method names in the user input file, then class names are also available

### Acceptance Criteria

```gherkin
Given a user a partition file and is going to run c2g
When the user provides an argument --partitions=<path/to/partitions.txt>
Then c2g will add partition id as a property for all class/method nodes in neo4j
```

**Comment by rofrano** [comment]
Implemented by CARGO
